"""
Django settings for OnlineBoardGamers project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from os.path import join
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
LOCAL_USER = config("LOCAL_USER", default=False, cast=bool)
LOCAL_USER_SQLITE3 = config("LOCAL_USER_SQLITE3", default=False, cast=bool)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG or LOCAL_USER:
    SECRET_KEY = config("SEECRET_KEY_HOME_SERVER")
else:
    SECRET_KEY = config("SECRET_KEY_PRODUCTION")

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60


if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Handled by cloudflare

    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [
        "https://www.onlineboardgamers.com",
        "https://onlineboardgamers.com",
        "https://webapp-1380192.pythonanywhere.com",
    ]
    USE_X_FORWARDED_HOST = False

    SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Or cached_db, or file, etc.
    SESSION_COOKIE_SECURE = True  # Only send the session cookie over HTTPS in production
    SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript from accessing the session cookie
    SESSION_COOKIE_SAMESITE = "Lax"  # Or 'Strict', depending on your needs

    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

LOGIN_URL = "myLogin"

if LOCAL_USER and DEBUG:
    ALLOWED_HOSTS = ["localhost", "192.168.1.2", "127.0.0.1"]
else:
    # ALLOWED_HOSTS = ['pythonanywhere']
    ALLOWED_HOSTS = [
        "www.onlineboardgamers.com",
        "onlineboardgamers.com",
        "webapp-1380192.pythonanywhere.com",
    ]

if LOCAL_USER:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST_USER = config("OBG_EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = config("OBG_EMAIL_APP_PWD")

EMAIL_TIMEOUT = 20  # This protects your CPU budget
EMAIL_HOST_USER_TURN = []
EMAIL_HOST_PASSWORD_TURN = []

# Email notifications for 500 errors
ADMINS = [
    ("Admin", config("OBG_EMAIL_HOST_USER")),
]
MANAGERS = ADMINS

# FIX: Safely splits "user@gmail.com" to produce "root@gmail.com"
email_user = config("OBG_EMAIL_HOST_USER")
if "@" in email_user:
    email_domain = email_user.split("@")[-1]
    SERVER_EMAIL = f"root@{email_domain}"
else:
    SERVER_EMAIL = f"root@{email_user}.com"

# Application definition

AUTH_USER_MODEL = "Lobby.User"
CSRF_FAILURE_VIEW = "Lobby.views.csrf_failure"

SITE_ID = 1

INSTALLED_APPS = [
    # 'FCM.apps.FCMConfig',
    # 'Lobby.apps.LobbyConfig',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "compressor",
    "django_q",
    "FCM",
    "Lobby",
    "user_visit",
    "BUS",
    "HLC",
    "TGZ",
    "CNS",
    "AQY",
    "IND",
    "KFW",
    "PPF",
    "WEB",
    "RNB",
    "statici18n",
    "i18n",
]

APPEND_SLASH = True

MIDDLEWARE = [
    # This MUST come first
    # 1. Always let security handle SSL/headers first
    "django.middleware.security.SecurityMiddleware",
    "Lobby.middleware.ForceTrailingSlashMiddleware",
    # This must come before Authentication and CsrfView
    "django.contrib.sessions.middleware.SessionMiddleware",
    # This must come after Session and Authentication
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    # This must come before AuthenticationM, and any permissions middleware
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "FCM.agent_auth.AgentTokenAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "user_visit.middleware.UserVisitMiddleware",
]

# Agent API calls use explicit bearer credentials and never create browser
# sessions. The visit recorder assumes an interactive session exists.
USER_VISIT_RECORDING_BYPASS = lambda request: request.path.startswith(
    "/FCM/agent/v1/"
)

ROOT_URLCONF = "OnlineBoardGamers.urls"

# Enable translation caching for better performance
USE_L10N = True
LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
]

# Translation cache settings
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Enable Django's built-in translation caching
def gettext_noop(x):
    return x


# 1. Make sure this folder name matches exactly what you created
JINJA2_CACHE_DIR = BASE_DIR / "jinja2_cache"

# 2. Force the creation of the folder if it's missing
if not JINJA2_CACHE_DIR.exists():
    import os

    os.makedirs(JINJA2_CACHE_DIR, exist_ok=True)

# Auto-discover Jinja2 template directories for all apps
JINJA2_TEMPLATE_DIRS = [BASE_DIR / "Lobby/jinja2"]

TEMPLATES = [
    {
        # --- JINJA2 (Using django-jinja for compatibility) ---
        "BACKEND": "django_jinja.backend.Jinja2",
        "NAME": "jinja2",  # <--- Add this
        "DIRS": JINJA2_TEMPLATE_DIRS,  # Auto-discovered Jinja2 template directories
        "APP_DIRS": True,
        "OPTIONS": {
            "match_extension": ".jinja",  # <--- CRITICAL
            "environment": "OnlineBoardGamers.jinja2.environment",
            # This allows {{ request }}, {{ user }}, etc. in Jinja
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "auto_reload": DEBUG,  # Always disable for performance
            "translation_engine": "django.utils.translation",
            ## Optimized Jinja2 Bytecode Cache settings
            "bytecode_cache": {
                "name": "jinja2_cache",
                "enabled": True,  # <--- CRITICAL
                "backend": "jinja2.FileSystemBytecodeCache",
                "dir": str(JINJA2_CACHE_DIR),  # Use the absolute path
                # "auto_reload": not DEBUG,  # Cache templates in production
            },
        },
    },
    {
        # --- STANDARD DJANGO (With RAM Caching) ---
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": False,  # Must be False to use the 'loaders' below
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
            ],
        },
    },
]

WSGI_APPLICATION = "OnlineBoardGamers.wsgi.application"

# JS Minifier settings
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",  # Add this
)
# Enable compression for production (even if DEBUG is False)
COMPRESS_ENABLED = True
if DEBUG:
    COMPRESS_ENABLED = False
COMPRESS_JS_FILTERS = ["compressor.filters.jsmin.JSMinFilter"]
COMPRESS_OFFLINE = True
if DEBUG:
    COMPRESS_OFFLINE = False
# END JS Minifier settings

# ASYNC SETTINGS
Q_CLUSTER = {
    "name": "obg_cluster",
    "label": "Django Q",  # Label in the admin panel
    "workers": 1,
    "timeout": 90,  # Process timeout - max time on task MUST BE LESS THAN RETRY VALUE
    "retry": 180,  # Must be bigger than time to complete longest task
    "orm": "default",  # Or your database alias
    "poll": 10,  # Check DB every 60 seconds (replaces your 'sleeptime' idea)
    "guard_cycle": 60,  # Max allowed value
    "cpu_affinity": 1,  # Forces the worker to stay on one core (Saves credits)
    "bulking": 10,  # Process up to 10 tasks in one go to minimize overhead
    "save_limit": 50,  # 0 is unlimited
    "ack_failures": True,  # Cleanup failed tasks
    "max_attempts": 3,  # Don't retry failed tasks multiple times
    "catch_up": False,  # Don't try to catch up on missed tasks
    "scheduler": True,  # Disables the scheduler loop entirely
    "recycle": 500,
    "sync": False,  # If true then removes the whole point of async. Testing only.
    "benchmark": False,  # Disable performance testing
    ############################################
    "queue_limit": 1,  # Defaults to workers**2
}

# NB this oculd kill very long DB connections
# socket.setdefaulttimeout(120)

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# if os.environ["DJANGO_DEBUG"] == True:
if LOCAL_USER_SQLITE3:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": config("SQLITE3_DB_PATH", default=BASE_DIR / "db.sqlite3"),
        }
    }
elif LOCAL_USER:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("LOCAL_DB_NAME"),
            "USER": config("LOCAL_DB_USER"),
            "PASSWORD": config("LOCAL_DB_PWD"),
            "HOST": config("LOCAL_DB_HOST"),
            "PORT": "3306",
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "OnlineGaming$default",
            "USER": "OnlineGaming",
            "PASSWORD": config("PRODUCTION_DB_PWD"),
            "HOST": "OnlineGaming.mysql.pythonanywhere-services.com",
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
# 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#   },
# {
#       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#   },
# ]

AUTH_PASSWORD_VALIDATORS = [
    # {
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 5,
        },
    },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

if DEBUG or LOCAL_USER:
    LANGUAGES = (
        ("en-gb", "English (United Kingdom)"),
        # ("zh-hans", gettext_noop("Simplified Chinese")),
        # ("zh-hans", "Simplified Chinese"),
        ("zh-hans", "简体中文"),
        ("es", "Spanish (Spain)"),
        ("de", "Deutsche"),
        # ('es', 'Spanish (Spain)'),
    )
else:
    LANGUAGES = (
        ("en-gb", "English (United Kingdom)"),
        ("zh-hans", "简体中文"),
    )


LANGUAGE_CODE = "en-gb"

LOCALE_PATHS = [
    join(BASE_DIR, "Lobby", "locale"),
    join(BASE_DIR, "FCM", "locale"),
    join(BASE_DIR, "HLC", "locale"),
]

# TIME_ZONE = 'Asia/Hong_Kong'
TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ── STATIC FILES  ──────────────────
STATIC_URL = "/static/"

# Source files (where Lobby/profile.js lives)
STATICFILES_DIRS = []

# Output folder for collectstatic (separate from source!)
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # → /home/OnlineGaming/.virtualenvs/OnlineGaming/staticfiles/

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",  # For media files
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Keep i18n if needed
STATICI18N_ROOT = BASE_DIR / "i18n" / "static"

# Where ViteJS assets are built.
# DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static" / "dist"

# If use HMR or not.
# DJANGO_VITE_DEV_MODE = DEBUG

# Name of static files folder (after called python manage.py collectstatic)
# SEE ABOVE
# STATIC_ROOT = BASE_DIR / "static"

# Include DJANGO_VITE_ASSETS_PATH into STATICFILES_DIRS to be copied inside
# when run command python manage.py collectstatic
# STATICFILES_DIRS = [DJANGO_VITE_ASSETS_PATH]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_DIR = os.path.join(BASE_DIR, "logs")

# Ensure log directory exists
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "handlers": {
        # The console handler for Docker/Kubernetes/Heroku
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "general_log_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "general.log"),
            "maxBytes": 11 * 1024 * 1024,  # 1 MB per file
            "backupCount": 5,  # Keep 5 backup files
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "fcm_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "FCM_views.log"),
            "maxBytes": 11 * 1024 * 1024,  # 1 MB per file
            "backupCount": 5,  # Keep 5 backup files (FCM_views.log.1, .2, etc.)
            "formatter": "standard",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # "django.db.backends": {
        #    "level": "DEBUG",
        # },
        "Lobby.views": {
            "handlers": ["general_log_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "FCM.models": {
            "handlers": ["general_log_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "FCM.admin": {
            "handlers": ["general_log_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "Lobby.middleware": {  # Add this for DebugSlashMiddleware
            "handlers": ["general_log_file", "console"],
            "level": "DEBUG",
            "propagate": False,  # Prevent propagation to root logger
        },
        "Lobby.utils": {
            "handlers": ["general_log_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "FCM.views": {
            "handlers": ["fcm_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
    "root": {
        "handlers": ["console"],
    },
}


if DEBUG:
    # Add to installed apps
    INSTALLED_APPS += ["debug_toolbar"]
    INSTALLED_APPS += ["template_profiler_panel"]

    # Add to middleware (must be near the top, but after GZipMiddleware)
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

    # Pyinstrument profiler - only in DEBUG
    MIDDLEWARE.append("pyinstrument.middleware.ProfilerMiddleware")

    # Required for the toolbar to show on localhost
    INTERNAL_IPS = ["127.0.0.1"]

    DEBUG_TOOLBAR_PANELS = [
        "debug_toolbar.panels.history.HistoryPanel",
        "debug_toolbar.panels.versions.VersionsPanel",
        "debug_toolbar.panels.timer.TimerPanel",
        "debug_toolbar.panels.settings.SettingsPanel",
        "debug_toolbar.panels.headers.HeadersPanel",
        "debug_toolbar.panels.request.RequestPanel",
        "debug_toolbar.panels.sql.SQLPanel",
        "debug_toolbar.panels.staticfiles.StaticFilesPanel",
        "debug_toolbar.panels.templates.TemplatesPanel",
        "template_profiler_panel.panels.template.TemplateProfilerPanel",  # <— Add this line
        "debug_toolbar.panels.cache.CachePanel",
        "debug_toolbar.panels.signals.SignalsPanel",
        "debug_toolbar.panels.redirects.RedirectsPanel",
        "debug_toolbar.panels.profiling.ProfilingPanel",
    ]

    def show_pyinstrument(request):
        allowed_usernames = ["admin", "h"]
        return request.user.is_authenticated and request.user.username in allowed_usernames

    PYINSTRUMENT_SHOW_CALLBACK = show_pyinstrument
